services:
  # ---- Backend Services ----
  redis_learning:
    image: redis:7.2-alpine
    container_name: redis_learning
    ports:
      - "6388:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - learning_net

  nats_learning:
    image: nats:2.10-alpine
    container_name: nats_learning
    ports:
      - "4229:4222"
    volumes:
      - ./nats-server.conf:/config/nats-server.conf
    command: ["-c", "/config/nats-server.conf"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - learning_net

  # ---- Learning GPU Services ----
  self_training_orchestrator:
    build:
      context: ../..
      dockerfile: docker/learning_gpu/Dockerfile
    image: learning_gpu:latest
    container_name: self_training_orchestrator
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5560:5560"
      - "6560:6560"
    environment:
      - AGENT_NAME=SelfTrainingOrchestrator
      - AGENT_PORT=5560
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      redis_learning:
        condition: service_healthy
      nats_learning:
        condition: service_started
    networks:
      - learning_net

  local_fine_tuner_agent:
    image: learning_gpu:latest
    container_name: local_fine_tuner_agent
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5561:5561"
      - "6561:6561"
    environment:
      - AGENT_NAME=LocalFineTunerAgent
      - AGENT_PORT=5561
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      self_training_orchestrator:
        condition: service_started
    networks:
      - learning_net

  learning_manager:
    image: learning_gpu:latest
    container_name: learning_manager
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5562:5562"
      - "6562:6562"
    environment:
      - AGENT_NAME=LearningManager
      - AGENT_PORT=5562
      - HEALTH_CHECK_PORT=6562
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      self_training_orchestrator:
        condition: service_started
    networks:
      - learning_net

  learning_orchestration_service:
    image: learning_gpu:latest
    container_name: learning_orchestration_service
    command: ["python", "-m", "main_pc_code.agents.learning_orchestration_service"]
    ports:
      - "5563:5563"
      - "6563:6563"
    environment:
      - AGENT_NAME=LearningOrchestrationService
      - AGENT_PORT=5563
      - HEALTH_CHECK_PORT=6563
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      self_training_orchestrator:
        condition: service_started
    networks:
      - learning_net

  learning_opportunity_detector:
    image: learning_gpu:latest
    container_name: learning_opportunity_detector
    command: ["python", "-m", "main_pc_code.agents.learning_opportunity_detector"]
    ports:
      - "5564:5564"
      - "6564:6564"
    environment:
      - AGENT_NAME=LearningOpportunityDetector
      - AGENT_PORT=5564
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      self_training_orchestrator:
        condition: service_started
    networks:
      - learning_net

  active_learning_monitor:
    image: learning_gpu:latest
    container_name: active_learning_monitor
    command: ["python", "-m", "main_pc_code.agents.active_learning_monitor"]
    ports:
      - "5565:5565"
      - "6565:6565"
    environment:
      - AGENT_NAME=ActiveLearningMonitor
      - AGENT_PORT=5565
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      self_training_orchestrator:
        condition: service_started
    networks:
      - learning_net

  learning_adjuster_agent:
    image: learning_gpu:latest
    container_name: learning_adjuster_agent
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5566:5566"
      - "6566:6566"
    environment:
      - AGENT_NAME=LearningAdjusterAgent
      - AGENT_PORT=5566
      - REDIS_URL=redis://redis_learning:6379
      - NATS_SERVERS=nats://nats_learning:4222
      - LOG_LEVEL=INFO
    depends_on:
      self_training_orchestrator:
        condition: service_started
    networks:
      - learning_net

networks:
  learning_net:
    driver: bridge
