version: '3.8'

services:
  go_t_to_t_agent:
    build:
      context: ../..
      dockerfile: docker/go_t_to_t_agent/Dockerfile
    command:
    - python
    - -m
    - main_pc_code.FORMAINPC.got_tot_agent
    container_name: go_t_to_t_agent
    environment:
      AGENT_NAME: GoTToTAgent
      AGENT_PORT: '5646'
      LOG_LEVEL: INFO
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6646/health
      timeout: 10s
    image: go_t_to_t_agent:latest
    networks:
    - go_t_to_t_agent_net
    ports:
    - 5646:5646
    - 6646:6646
    restart: unless-stopped

networks:
  go_t_to_t_agent_net:
    driver: bridge