global_settings:
  environment:
    PYTHONPATH: /app
    LOG_LEVEL: INFO
    DEBUG_MODE: 'false'
    ENABLE_METRICS: 'true'
    ENABLE_TRACING: 'true'
    ENABLE_DATA_OPTIMIZER: 'true'
    DATA_OPTIMIZER_METHOD: compressed_msgpack
  resource_limits:
    cpu_percent: 80
    memory_mb: 2048
    max_threads: 4
  health_checks:
    interval_seconds: 30
    timeout_seconds: 10
    retries: 3
agent_groups:
  core_services:
    ServiceRegistry:
      script_path: src/agents/mainpc/service_registry_agent.py
      port: ${PORT_OFFSET}+7200
      health_check_port: ${PORT_OFFSET}+8200
      required: true
      dependencies: []
      config:
        backend: memory
        redis:
          url: redis://localhost:6379/0
          prefix: 'service_registry:'
    SystemDigitalTwin:
      script_path: src/agents/mainpc/system_digital_twin.py
      port: ${PORT_OFFSET}+7220
      health_check_port: ${PORT_OFFSET}+8220
      config:
        db_path: data/unified_memory.db
        redis:
          host: localhost
          port: ${PORT_OFFSET}+6379
          db: 0
        zmq_request_timeout: 5000
      required: true
      dependencies:
      - ServiceRegistry
    RequestCoordinator:
      script_path: src/agents/mainpc/request_coordinator.py
      port: 26002
      health_check_port: 27002
      required: true
      dependencies:
      - SystemDigitalTwin
    UnifiedSystemAgent:
      script_path: src/agents/mainpc/unified_system_agent.py
      port: ${PORT_OFFSET}+7225
      health_check_port: ${PORT_OFFSET}+8225
      required: true
      dependencies:
      - SystemDigitalTwin
    ObservabilityHub:
      script_path: src/agents/core/observability_hub.py
      port: ${PORT_OFFSET}+9000
      health_check_port: ${PORT_OFFSET}+9001
      required: true
      dependencies:
      - SystemDigitalTwin
      config:
        prometheus_enabled: true
        parallel_health_checks: true
        prediction_enabled: true
    ModelManagerSuite:
      script_path: src/agents/mainpc/model_manager_suite.py
      port: ${PORT_OFFSET}+7211
      health_check_port: ${PORT_OFFSET}+8211
      required: true
      dependencies:
      - SystemDigitalTwin
      config:
        models_dir: models
        vram_budget_percentage: 80
        idle_timeout: 300
  memory_system:
    MemoryClient:
      script_path: src/agents/mainpc/memory_client.py
      port: ${PORT_OFFSET}+5713
      health_check_port: ${PORT_OFFSET}+6713
      required: true
      dependencies:
      - SystemDigitalTwin
    SessionMemoryAgent:
      script_path: src/agents/mainpc/session_memory_agent.py
      port: ${PORT_OFFSET}+5574
      health_check_port: ${PORT_OFFSET}+6574
      required: true
      dependencies:
      - RequestCoordinator
      - SystemDigitalTwin
      - MemoryClient
    KnowledgeBase:
      script_path: src/agents/mainpc/knowledge_base.py
      port: ${PORT_OFFSET}+5715
      health_check_port: ${PORT_OFFSET}+6715
      required: true
      dependencies:
      - MemoryClient
      - SystemDigitalTwin
  utility_services:
    CodeGenerator:
      script_path: src/agents/mainpc/code_generator_agent.py
      port: ${PORT_OFFSET}+5650
      health_check_port: ${PORT_OFFSET}+6650
      required: true
      dependencies:
      - SystemDigitalTwin
      - ModelManagerSuite
    SelfTrainingOrchestrator:
      script_path: src/agents/mainpc/formainpc/SelfTrainingOrchestrator.py
      port: ${PORT_OFFSET}+5660
      health_check_port: ${PORT_OFFSET}+6660
      required: true
      dependencies:
      - SystemDigitalTwin
      - ModelManagerSuite
    PredictiveHealthMonitor:
      script_path: src/agents/mainpc/predictive_health_monitor.py
      port: ${PORT_OFFSET}+5613
      health_check_port: ${PORT_OFFSET}+6613
      required: true
      dependencies:
      - SystemDigitalTwin
    FixedStreamingTranslation:
      script_path: src/agents/mainpc/fixed_streaming_translation.py
      port: ${PORT_OFFSET}+5584
      health_check_port: ${PORT_OFFSET}+6584
      required: true
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
    Executor:
      script_path: src/agents/mainpc/executor.py
      port: ${PORT_OFFSET}+5606
      health_check_port: ${PORT_OFFSET}+6606
      required: true
      dependencies:
      - CodeGenerator
      - SystemDigitalTwin
    TinyLlamaServiceEnhanced:
      script_path: src/agents/mainpc/formainpc/TinyLlamaServiceEnhanced.py
      port: ${PORT_OFFSET}+5615
      health_check_port: ${PORT_OFFSET}+6615
      required: false
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
    LocalFineTunerAgent:
      script_path: src/agents/mainpc/formainpc/LocalFineTunerAgent.py
      port: ${PORT_OFFSET}+5642
      health_check_port: ${PORT_OFFSET}+6642
      required: true
      dependencies:
      - SelfTrainingOrchestrator
      - SystemDigitalTwin
    NLLBAdapter:
      script_path: src/agents/mainpc/formainpc/NLLBAdapter.py
      port: ${PORT_OFFSET}+5581
      health_check_port: ${PORT_OFFSET}+6581
      required: true
      dependencies:
      - SystemDigitalTwin
  gpu_infrastructure:
    VRAMOptimizerAgent:
      script_path: src/agents/mainpc/vram_optimizer_agent.py
      port: ${PORT_OFFSET}+5572
      health_check_port: ${PORT_OFFSET}+6572
      required: true
      dependencies:
      - ModelManagerSuite
      - RequestCoordinator
      - SystemDigitalTwin
  reasoning_services:
    ChainOfThoughtAgent:
      script_path: src/agents/mainpc/formainpc/ChainOfThoughtAgent.py
      port: ${PORT_OFFSET}+5612
      health_check_port: ${PORT_OFFSET}+6612
      required: true
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
    GoTToTAgent:
      script_path: src/agents/mainpc/formainpc/GOT_TOTAgent.py
      port: ${PORT_OFFSET}+5646
      health_check_port: ${PORT_OFFSET}+6646
      required: false
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
      - ChainOfThoughtAgent
    CognitiveModelAgent:
      script_path: src/agents/mainpc/formainpc/CognitiveModelAgent.py
      port: ${PORT_OFFSET}+5641
      health_check_port: ${PORT_OFFSET}+6641
      required: false
      dependencies:
      - ChainOfThoughtAgent
      - SystemDigitalTwin
  vision_processing:
    FaceRecognitionAgent:
      script_path: src/agents/mainpc/face_recognition_agent.py
      port: ${PORT_OFFSET}+5610
      health_check_port: ${PORT_OFFSET}+6610
      required: true
      dependencies:
      - RequestCoordinator
      - ModelManagerSuite
      - SystemDigitalTwin
  learning_knowledge:
    LearningOrchestrationService:
      script_path: src/agents/mainpc/learning_orchestration_service.py
      port: ${PORT_OFFSET}+7210
      health_check_port: ${PORT_OFFSET}+8212
      required: true
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
    LearningOpportunityDetector:
      script_path: src/agents/mainpc/learning_opportunity_detector.py
      port: ${PORT_OFFSET}+7202
      health_check_port: ${PORT_OFFSET}+8202
      required: true
      dependencies:
      - LearningOrchestrationService
      - MemoryClient
      - SystemDigitalTwin
    LearningManager:
      script_path: src/agents/mainpc/learning_manager.py
      port: ${PORT_OFFSET}+5580
      health_check_port: ${PORT_OFFSET}+6580
      required: true
      dependencies:
      - MemoryClient
      - RequestCoordinator
      - SystemDigitalTwin
    ActiveLearningMonitor:
      script_path: src/agents/mainpc/active_learning_monitor.py
      port: ${PORT_OFFSET}+5638
      health_check_port: ${PORT_OFFSET}+6638
      required: true
      dependencies:
      - LearningManager
      - SystemDigitalTwin
    LearningAdjusterAgent:
      script_path: src/agents/mainpc/formainpc/LearningAdjusterAgent.py
      port: ${PORT_OFFSET}+5643
      health_check_port: ${PORT_OFFSET}+6643
      required: true
      dependencies:
      - SelfTrainingOrchestrator
      - SystemDigitalTwin
  language_processing:
    ModelOrchestrator:
      script_path: src/agents/mainpc/model_orchestrator.py
      port: ${PORT_OFFSET}+7213
      health_check_port: ${PORT_OFFSET}+8213
      required: true
      dependencies:
      - RequestCoordinator
      - ModelManagerSuite
      - SystemDigitalTwin
    GoalManager:
      script_path: src/agents/mainpc/goal_manager.py
      port: ${PORT_OFFSET}+7205
      health_check_port: ${PORT_OFFSET}+8205
      required: true
      dependencies:
      - RequestCoordinator
      - ModelOrchestrator
      - SystemDigitalTwin
      - MemoryClient
    IntentionValidatorAgent:
      script_path: src/agents/mainpc/IntentionValidatorAgent.py
      port: ${PORT_OFFSET}+5701
      health_check_port: ${PORT_OFFSET}+6701
      required: true
      dependencies:
      - RequestCoordinator
      - SystemDigitalTwin
    NLUAgent:
      script_path: src/agents/mainpc/nlu_agent.py
      port: ${PORT_OFFSET}+5709
      health_check_port: ${PORT_OFFSET}+6709
      required: true
      dependencies:
      - SystemDigitalTwin
    AdvancedCommandHandler:
      script_path: src/agents/mainpc/advanced_command_handler.py
      port: ${PORT_OFFSET}+5710
      health_check_port: ${PORT_OFFSET}+6710
      required: true
      dependencies:
      - NLUAgent
      - CodeGenerator
      - SystemDigitalTwin
    ChitchatAgent:
      script_path: src/agents/mainpc/chitchat_agent.py
      port: ${PORT_OFFSET}+5711
      health_check_port: ${PORT_OFFSET}+6711
      required: true
      dependencies:
      - NLUAgent
      - SystemDigitalTwin
    FeedbackHandler:
      script_path: src/agents/mainpc/feedback_handler.py
      port: ${PORT_OFFSET}+5636
      health_check_port: ${PORT_OFFSET}+6636
      required: true
      dependencies:
      - NLUAgent
      - SystemDigitalTwin
    Responder:
      script_path: src/agents/mainpc/responder.py
      port: ${PORT_OFFSET}+5637
      health_check_port: ${PORT_OFFSET}+6637
      required: true
      dependencies:
      - EmotionEngine
      - FaceRecognitionAgent
      - NLUAgent
      - StreamingTTSAgent
      - SystemDigitalTwin
      - TTSService
    TranslationService:
      script_path: src/agents/mainpc/translation_service.py
      port: ${PORT_OFFSET}+5595
      health_check_port: ${PORT_OFFSET}+6595
      required: true
      dependencies:
      - SystemDigitalTwin
    DynamicIdentityAgent:
      script_path: src/agents/mainpc/DynamicIdentityAgent.py
      port: ${PORT_OFFSET}+5802
      health_check_port: ${PORT_OFFSET}+6802
      required: true
      dependencies:
      - RequestCoordinator
      - SystemDigitalTwin
    EmotionSynthesisAgent:
      script_path: src/agents/mainpc/emotion_synthesis_agent.py
      port: ${PORT_OFFSET}+5706
      health_check_port: ${PORT_OFFSET}+6706
      required: true
      dependencies:
      - RequestCoordinator
      - ModelManagerSuite
      - SystemDigitalTwin
  speech_services:
    STTService:
      script_path: src/agents/mainpc/services/stt_service.py
      port: ${PORT_OFFSET}+5800
      health_check_port: ${PORT_OFFSET}+6800
      required: true
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
    TTSService:
      script_path: src/agents/mainpc/services/tts_service.py
      port: ${PORT_OFFSET}+5801
      health_check_port: ${PORT_OFFSET}+6801
      required: true
      dependencies:
      - ModelManagerSuite
      - SystemDigitalTwin
  audio_interface:
    AudioCapture:
      script_path: src/agents/mainpc/streaming_audio_capture.py
      port: ${PORT_OFFSET}+6550
      health_check_port: ${PORT_OFFSET}+7550
      required: true
      dependencies:
      - SystemDigitalTwin
    FusedAudioPreprocessor:
      script_path: src/agents/mainpc/fused_audio_preprocessor.py
      port: ${PORT_OFFSET}+6551
      health_check_port: ${PORT_OFFSET}+7551
      required: true
      dependencies:
      - AudioCapture
      - SystemDigitalTwin
    StreamingInterruptHandler:
      script_path: src/agents/mainpc/streaming_interrupt_handler.py
      port: ${PORT_OFFSET}+5576
      health_check_port: ${PORT_OFFSET}+6576
      required: true
      dependencies:
      - StreamingSpeechRecognition
      - StreamingTTSAgent
      - SystemDigitalTwin
    StreamingSpeechRecognition:
      script_path: src/agents/mainpc/streaming_speech_recognition.py
      port: ${PORT_OFFSET}+6553
      health_check_port: ${PORT_OFFSET}+7553
      required: true
      dependencies:
      - FusedAudioPreprocessor
      - RequestCoordinator
      - STTService
      - SystemDigitalTwin
    StreamingTTSAgent:
      script_path: src/agents/mainpc/streaming_tts_agent.py
      port: ${PORT_OFFSET}+5562
      health_check_port: ${PORT_OFFSET}+6562
      required: true
      dependencies:
      - RequestCoordinator
      - TTSService
      - SystemDigitalTwin
      - UnifiedSystemAgent
    WakeWordDetector:
      script_path: src/agents/mainpc/wake_word_detector.py
      port: ${PORT_OFFSET}+6552
      health_check_port: ${PORT_OFFSET}+7552
      required: true
      dependencies:
      - AudioCapture
      - FusedAudioPreprocessor
      - SystemDigitalTwin
    StreamingLanguageAnalyzer:
      script_path: src/agents/mainpc/streaming_language_analyzer.py
      port: ${PORT_OFFSET}+5579
      health_check_port: ${PORT_OFFSET}+6579
      required: true
      dependencies:
      - StreamingSpeechRecognition
      - SystemDigitalTwin
      - TranslationService
    ProactiveAgent:
      script_path: src/agents/mainpc/ProactiveAgent.py
      port: ${PORT_OFFSET}+5624
      health_check_port: ${PORT_OFFSET}+6624
      required: true
      dependencies:
      - RequestCoordinator
      - SystemDigitalTwin
  emotion_system:
    EmotionEngine:
      script_path: src/agents/mainpc/emotion_engine.py
      port: ${PORT_OFFSET}+5590
      health_check_port: ${PORT_OFFSET}+6590
      required: true
      dependencies:
      - SystemDigitalTwin
    MoodTrackerAgent:
      script_path: src/agents/mainpc/mood_tracker_agent.py
      port: ${PORT_OFFSET}+5704
      health_check_port: ${PORT_OFFSET}+6704
      required: true
      dependencies:
      - EmotionEngine
      - SystemDigitalTwin
    HumanAwarenessAgent:
      script_path: src/agents/mainpc/human_awareness_agent.py
      port: ${PORT_OFFSET}+5705
      health_check_port: ${PORT_OFFSET}+6705
      required: true
      dependencies:
      - EmotionEngine
      - SystemDigitalTwin
    ToneDetector:
      script_path: src/agents/mainpc/tone_detector.py
      port: ${PORT_OFFSET}+5625
      health_check_port: ${PORT_OFFSET}+6625
      required: true
      dependencies:
      - EmotionEngine
      - SystemDigitalTwin
    VoiceProfilingAgent:
      script_path: src/agents/mainpc/voice_profiling_agent.py
      port: ${PORT_OFFSET}+5708
      health_check_port: ${PORT_OFFSET}+6708
      required: true
      dependencies:
      - EmotionEngine
      - SystemDigitalTwin
    EmpathyAgent:
      script_path: src/agents/mainpc/EmpathyAgent.py
      port: ${PORT_OFFSET}+5703
      health_check_port: ${PORT_OFFSET}+6703
      required: true
      dependencies:
      - EmotionEngine
      - StreamingTTSAgent
      - SystemDigitalTwin
