version: '3.8'

services:
  debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: ai-system-debug
    volumes:
      - ./:/app
    working_dir: /app
    command: python test_imports.py 