version: '3.8'

services:
  # Foundation Services Test Environment
  foundation-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.foundation-test
    container_name: foundation-services-test
    environment:
      - PYTHONPATH=/app
      - PORT_OFFSET=0
      - LOG_LEVEL=INFO
      - DEBUG_MODE=false
      - ENABLE_METRICS=true
      - ENABLE_TRACING=true
      - ENABLE_HYBRID_INFERENCE=true
      - HYBRID_QUALITY_THRESHOLD=0.85
      # Test-specific environment variables
      - TEST_MODE=true
      - SKIP_GPU_CHECKS=true
      - MOCK_MODELS=true
      - HEALTH_CHECK_TIMEOUT=30
    ports:
      # Foundation Services Ports
      - "7200:7200"   # ServiceRegistry
      - "8200:8200"   # ServiceRegistry Health
      - "7220:7220"   # SystemDigitalTwin
      - "8220:8220"   # SystemDigitalTwin Health
      - "26002:26002" # RequestCoordinator
      - "27002:27002" # RequestCoordinator Health
      - "7211:7211"   # ModelManagerSuite
      - "8211:8211"   # ModelManagerSuite Health
      - "5572:5572"   # VRAMOptimizerAgent
      - "6572:6572"   # VRAMOptimizerAgent Health
      - "9000:9000"   # ObservabilityHub
      - "9001:9001"   # ObservabilityHub Health
      - "7201:7201"   # UnifiedSystemAgent
      - "8201:8201"   # UnifiedSystemAgent Health
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    networks:
      - foundation-test-network
    healthcheck:
      test: ["CMD", "python3", "/app/test/health_check_foundation.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: ["python3", "/app/test/start_foundation_services.py"]

  # Redis for ServiceRegistry (optional, uses memory by default)
  redis-test:
    image: redis:7-alpine
    container_name: foundation-redis-test
    ports:
      - "6379:6379"
    networks:
      - foundation-test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  foundation-test-network:
    driver: bridge 