version: "3.8"
services:
  nats-1:
    image: nats:2.10
    command: ["-js", "-p", "4222", "-cluster", "nats://0.0.0.0:6222", "-routes", "nats://nats-2:6222,nats://nats-3:6222"]
    ports: ["4222:4222"]
  nats-2:
    image: nats:2.10
    command: ["-js", "-p", "4222", "-cluster", "nats://0.0.0.0:6222", "-routes", "nats://nats-1:6222,nats://nats-3:6222"]
  nats-3:
    image: nats:2.10
    command: ["-js", "-p", "4222", "-cluster", "nats://0.0.0.0:6222", "-routes", "nats://nats-1:6222,nats://nats-2:6222"]

  uoc-a:
    build: .
    command: ["bash", "-lc", "UOC_API_TOKENS=devtoken python -m unified_observability_center.app"]
    environment:
      - UOC_API_TOKENS=devtoken
    depends_on:
      - nats-1
      - nats-2
      - nats-3
    ports: ["9100:9100"]
  uoc-b:
    build: .
    command: ["bash", "-lc", "UOC_API_TOKENS=devtoken python -m unified_observability_center.app"]
    environment:
      - UOC_API_TOKENS=devtoken
    depends_on:
      - nats-1
      - nats-2
      - nats-3
    ports: ["9101:9100"]