services:
  minimal:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: ai-system-minimal
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: python test_simple.py 