version: "3.9"

# Production secrets management overlay
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d

secrets:
  openai_api_key:
    external: true
    name: ai_system_openai_key
  anthropic_api_key:
    external: true
    name: ai_system_anthropic_key
  database_password:
    external: true
    name: ai_system_db_password
  redis_password:
    external: true
    name: ai_system_redis_password
  tls_cert:
    external: true
    name: ai_system_tls_cert
  tls_key:
    external: true
    name: ai_system_tls_key

services:
  coordination:
    secrets:
      - openai_api_key
      - anthropic_api_key
    environment:
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic_api_key

  memory_stack:
    secrets:
      - database_password
    environment:
      - DB_PASSWORD_FILE=/run/secrets/database_password

  observability:
    secrets:
      - tls_cert
      - tls_key
    environment:
      - TLS_CERT_FILE=/run/secrets/tls_cert
      - TLS_KEY_FILE=/run/secrets/tls_key

  # Override for PC2 services
  pc2_memory_stack:
    secrets:
      - database_password
      - redis_password
    environment:
      - DB_PASSWORD_FILE=/run/secrets/database_password
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password