version: "3.9"
services:
  # PC2-resident services
  mfh:
    build: ./memory_fusion_hub
    networks: [core_net]
    environment:
      ROLE: "authoritative"

  rtap-pre:
    build: ./real_time_audio_pipeline
    networks: [core_net]
    environment:
      RTAP_ENVIRONMENT: "pc2"
      RTAP_LOG_LEVEL: "INFO"
      # Emits frames to ZMQ for MainPC consumer
      # Publisher ports are in RTAP config

  uoc-edge:
    build: ./unified_observability_center
    environment: { ROLE: "edge" }
    networks: [core_net]

  # MainPC-resident services
  moc:
    build: ./model_ops_coordinator
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks: [core_net]

  apc:
    build: ./affective_processing_center
    depends_on: [moc]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks: [core_net]
    environment:
      MFH_PROXY_ADDR: "mfh-proxy:5715"

  rtap-gpu:
    build: ./real_time_audio_pipeline
    depends_on: [moc]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks: [core_net]
    environment:
      RTAP_ENVIRONMENT: "main_pc"
      RTAP_INPUT_HOST: "rtap-pre"  # consume frames from PC2

  mfh-proxy:
    build: ./memory_fusion_hub/proxy
    depends_on: [mfh]
    networks: [core_net]
    environment:
      TARGET_MFH_HOST: "mfh"
      TARGET_MFH_PORT: "5714"
      CACHE_TTL_SEC: "60"
      PROXY_GRPC_PORT: "5715"

  uoc-central:
    build: ./unified_observability_center
    environment: { ROLE: "central" }
    networks: [core_net]

networks:
  core_net: { driver: bridge }

