version: '3.8'

networks:
  ai-network:
    driver: bridge

services:
  # Group 1: Core Services
  system-digital-twin:
    build:
      context: .
      dockerfile: main_pc_code/agents/Dockerfile
    container_name: system-digital-twin
    networks:
      - ai-network
    ports:
      - "7120:7120"
      - "7121:7121"
    environment:
      - AGENT_NAME=SystemDigitalTwin
      - PORT=7120
      - HEALTH_CHECK_PORT=7121
    volumes:
      - ./main_pc_code:/app/main_pc_code
      - ./logs:/app/logs
    command: ["python", "main_pc_code/agents/system_digital_twin.py"]

  model-manager:
    build:
      context: .
      dockerfile: main_pc_code/agents/Dockerfile
    container_name: model-manager
    networks:
      - ai-network
    ports:
      - "5570:5570"
      - "5571:5571"
    environment:
      - AGENT_NAME=ModelManagerAgent
      - PORT=5570
      - HEALTH_CHECK_PORT=5571
    volumes:
      - ./main_pc_code:/app/main_pc_code
      - ./models:/app/models
    depends_on:
      - system-digital-twin

  coordinator:
    build:
      context: .
      dockerfile: main_pc_code/agents/Dockerfile
    container_name: coordinator
    networks:
      - ai-network
    ports:
      - "26002:26002"
      - "26003:26003"
    environment:
      - AGENT_NAME=CoordinatorAgent
      - PORT=26002
      - HEALTH_CHECK_PORT=26003
    volumes:
      - ./main_pc_code:/app/main_pc_code
    depends_on:
      - model-manager

  # Group 2: AI/ML Services
  chain-of-thought:
    build:
      context: .
      dockerfile: main_pc_code/FORMAINPC/Dockerfile
    container_name: chain-of-thought
    networks:
      - ai-network
    ports:
      - "5612:5612"
      - "5613:5613"
    environment:
      - AGENT_NAME=ChainOfThoughtAgent
      - PORT=5612
      - HEALTH_CHECK_PORT=5613
    volumes:
      - ./main_pc_code:/app/main_pc_code
      - ./models:/app/models
    depends_on:
      - coordinator

  got-tot-agent:
    build:
      context: .
      dockerfile: main_pc_code/FORMAINPC/Dockerfile
    container_name: got-tot-agent
    networks:
      - ai-network
    ports:
      - "7000:7000"
      - "7001:7001"
    environment:
      - AGENT_NAME=GoTToTAgent
      - PORT=7000
      - HEALTH_CHECK_PORT=7001
    volumes:
      - ./main_pc_code:/app/main_pc_code
    depends_on:
      - coordinator

  self-training-orchestrator:
    build:
      context: .
      dockerfile: main_pc_code/FORMAINPC/Dockerfile
    container_name: self-training-orchestrator
    networks:
      - ai-network
    ports:
      - "5644:5644"
      - "5645:5645"
    environment:
      - AGENT_NAME=SelfTrainingOrchestrator
      - PORT=5644
      - HEALTH_CHECK_PORT=5645
    volumes:
      - ./main_pc_code:/app/main_pc_code
      - ./training_data:/app/training_data
    depends_on:
      - coordinator

  # Group 3: Audio/Emotion Services
  emotion-engine:
    build:
      context: .
      dockerfile: main_pc_code/agents/Dockerfile
    container_name: emotion-engine
    networks:
      - ai-network
    ports:
      - "5590:5590"
      - "5591:5591"
    environment:
      - AGENT_NAME=EmotionEngine
      - PORT=5590
      - HEALTH_CHECK_PORT=5591
    volumes:
      - ./main_pc_code:/app/main_pc_code
    depends_on:
      - coordinator

  audio-capture:
    build:
      context: .
      dockerfile: main_pc_code/agents/Dockerfile
    container_name: audio-capture
    networks:
      - ai-network
    ports:
      - "6575:6575"
      - "6576:6576"
    environment:
      - AGENT_NAME=AudioCapture
      - PORT=6575
      - HEALTH_CHECK_PORT=6576
      - USE_DUMMY_AUDIO=true
    volumes:
      - ./main_pc_code:/app/main_pc_code
      - ./audio_data:/app/audio_data
    depends_on:
      - coordinator

  # Health Check Service
  health-checker:
    build:
      context: .
      dockerfile: main_pc_code/NEWMUSTFOLLOW/Dockerfile
    container_name: health-checker
    networks:
      - ai-network
    environment:
      - CONFIG_PATH=/app/main_pc_code/NEWMUSTFOLLOW/minimal_system_config_local.yaml
    volumes:
      - ./main_pc_code:/app/main_pc_code
      - ./logs:/app/logs
    command: ["python", "main_pc_code/NEWMUSTFOLLOW/check_mvs_health.py"]
    depends_on:
      - system-digital-twin
      - model-manager
      - coordinator
      - chain-of-thought
      - got-tot-agent
      - self-training-orchestrator
      - emotion-engine
      - audio-capture 