version: "3.9"

# Test profile for end-to-end testing with lightweight configurations
# Usage: docker-compose -f docker-compose.test.yml up -d

services:
  # Test databases and storage
  test_redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1

  test_postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_memory
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"

  # Minimal core services for testing
  test_infra_core:
    image: ai_system/infra_core:latest
    environment:
      - PYTHONPATH=/app
      - PORT_OFFSET=20000
      - TEST_MODE=true
    ports:
      - "28200:28200"
    depends_on:
      - test_redis
    healthcheck:
      test: ["CMD", "python3", "scripts/health_probe.py", "--url", "http://localhost:28200/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  test_memory_stack:
    image: ai_system/memory_stack:latest
    environment:
      - PYTHONPATH=/app
      - PORT_OFFSET=20000
      - TEST_MODE=true
      - DB_URL=postgresql://testuser:testpass@test_postgres:5432/test_memory
    ports:
      - "26713:26713"
    depends_on:
      - test_infra_core
      - test_postgres
    healthcheck:
      test: ["CMD", "python3", "scripts/health_probe.py", "--url", "http://localhost:26713/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  test_language_stack:
    image: ai_system/language_stack:latest
    environment:
      - PYTHONPATH=/app
      - PORT_OFFSET=20000
      - TEST_MODE=true
      - MOCK_LLM=true
    ports:
      - "25709:25709"
    depends_on:
      - test_memory_stack
    healthcheck:
      test: ["CMD", "python3", "scripts/health_probe.py", "--url", "http://localhost:25709/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Test runner container
  e2e_test_runner:
    build:
      context: .
      dockerfile: tests/e2e/Dockerfile
    environment:
      - PYTHONPATH=/app
      - TEST_INFRA_URL=http://test_infra_core:28200
      - TEST_MEMORY_URL=http://test_memory_stack:26713
      - TEST_LANGUAGE_URL=http://test_language_stack:25709
    depends_on:
      test_infra_core:
        condition: service_healthy
      test_memory_stack:
        condition: service_healthy
      test_language_stack:
        condition: service_healthy
    volumes:
      - ./tests:/app/tests
      - ./test_results:/app/test_results
    command: >
      bash -c "
        echo 'Waiting for services to be ready...' &&
        sleep 10 &&
        python -m pytest tests/e2e/ -v --tb=short --junit-xml=/app/test_results/junit.xml
      "

networks:
  default:
    name: test_agent_net