version: "3.9"

x-default-logging: &default_logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-default-health: &default_health
  interval: 30s
  timeout: 10s
  retries: 3

services:
  # ---------------------------------------------------------------------------
  # Core infrastructure
  # ---------------------------------------------------------------------------
  infra_core:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ai_system/infra_core:latest
    depends_on: {}
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}8200/health"]
      <<: *default_health
    networks:
      - agent_net

  coordination:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ai_system/coordination:latest
    depends_on:
      - infra_core
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: ["gpu"]
        limits:
          cpus: "4.0"
          memory: 8g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}8211/health"]
      <<: *default_health
    networks:
      - agent_net

  observability:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ai_system/observability_hub:latest
    depends_on:
      - infra_core
    environment:
      - PROMETHEUS_PORT=${PORT_OFFSET:-0}9000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}9001/health"]
      <<: *default_health
    networks:
      - agent_net

  memory_stack:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ai_system/memory_stack:latest
    depends_on:
      - infra_core
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}6713/health"]
      <<: *default_health
    networks:
      - agent_net

  vision_gpu:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ai_system/vision_suite:latest
    depends_on:
      - coordination
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: ["gpu"]
        limits:
          cpus: "4.0"
          memory: 6g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}6610/health"]
      <<: *default_health
    networks:
      - agent_net

  speech_gpu:
    image: ai_system/speech_pipeline:latest
    depends_on:
      - coordination
      - vision_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: ["gpu"]
        limits:
          cpus: "4.0"
          memory: 6g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}6800/health"]
      <<: *default_health
    networks:
      - agent_net

  learning_gpu:
    image: ai_system/learning_pipeline:latest
    depends_on:
      - coordination
      - memory_stack
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: ["gpu"]
        limits:
          cpus: "6.0"
          memory: 10g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}5580/health"]
      <<: *default_health
    networks:
      - agent_net

  reasoning_gpu:
    image: ai_system/reasoning_suite:latest
    depends_on:
      - coordination
      - memory_stack
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: ["gpu"]
        limits:
          cpus: "4.0"
          memory: 8g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}6612/health"]
      <<: *default_health
    networks:
      - agent_net

  language_stack:
    image: ai_system/language_stack:latest
    depends_on:
      - memory_stack
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 6g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}5709/health"]
      <<: *default_health
    networks:
      - agent_net

  utility_cpu:
    image: ai_system/utility_suite:latest
    depends_on:
      - infra_core
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}5650/health"]
      <<: *default_health
    networks:
      - agent_net

  emotion_system:
    image: ai_system/emotion_system:latest
    depends_on:
      - language_stack
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    logging: *default_logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_OFFSET:-0}6590/health"]
      <<: *default_health
    networks:
      - agent_net

networks:
  agent_net:
    driver: bridge