[build]
  command = "echo 'No build step required for Python Flask app'"
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "python app.py"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.10"
  FLASK_ENV = "production"
