# MainPC Configuration Override
# RTX 4090 - 24GB VRAM - High Performance AI Processing
# Machine Type: MAIN_PC / mainpc

# Environment detection
environment:
  MACHINE_TYPE: mainpc
  MACHINE_ROLE: MAIN_PC
  GPU_TIER: high_end
  DOCKER_CONTAINER: "${DOCKER_CONTAINER:-false}"

# Resource limits optimized for RTX 4090
resource_limits:
  vram_gb: 24
  memory_mb: 8192
  cpu_percent: 90
  max_concurrent_agents: 54

# GPU settings for RTX 4090
gpu_settings:
  layers: 50
  cuda_version: "8.6"
  optimization_level: high
  tensor_parallel_size: 2
  gpu_memory_fraction: 0.9
  enable_mixed_precision: true

# Agent group configurations for MainPC
agent_groups:
  core_services:
    resource_multiplier: 1.2
    priority: high
    
  gpu_infrastructure:
    resource_multiplier: 2.0
    priority: critical
    gpu_exclusive: true
    
  reasoning_services:
    resource_multiplier: 1.8
    priority: high
    gpu_layers: 40
    
  vision_processing:
    resource_multiplier: 1.5
    priority: medium
    gpu_layers: 35
    
  language_processing:
    resource_multiplier: 1.3
    priority: medium
    gpu_layers: 30

# Machine-specific agent configurations
agents:
  ModelManagerSuite:
    config:
      vram_limit_gb: 20
      model_cache_size: 8
      concurrent_models: 4
      
  VRAMOptimizerAgent:
    config:
      optimization_mode: aggressive
      memory_threshold: 0.85
      
  ChainOfThoughtAgent:
    config:
      max_reasoning_depth: 10
      parallel_chains: 3

# Network configuration for MainPC
network:
  interface: "192.168.1.0/24"
  port_range: "5000-8999"
  pc2_endpoint: "${PC2_ENDPOINT:-http://pc2:9000}"
  
# Cross-machine communication
cross_machine:
  pc2_host: "${PC2_IP:-pc2}"
  sync_interval: 15
  primary_role: true

# Logging configuration
logging:
  level: INFO
  max_file_size: "100MB"
  backup_count: 10
  
# Health check settings
health_checks:
  interval: 30
  timeout: 10
  enabled: true