networks:
  emotion_engine_net:
    driver: bridge
services:
  emotion_engine:
    build:
      context: ../..
      dockerfile: docker/emotion_engine/Dockerfile
    command:
    - python
    - -m
    - main_pc_code.agents.emotion_engine
    container_name: emotion_engine
    depends_on:
    - redis_emotion
    - nats_emotion
    environment:
      LOG_LEVEL: INFO
      NATS_SERVERS: nats://nats_emotion:4222
      REDIS_URL: redis://redis_emotion:6379/0
      SERVICE_REGISTRY_REDIS_URL: redis://redis_emotion:6379/0
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6590/health
      timeout: 10s
    image: emotion_engine:latest
    networks:
    - emotion_engine_net
    ports:
    - 5590:5590
    - 6590:6590
    restart: unless-stopped
version: '3.8'
