networks:
  pc2_experience_tracker_net:
    driver: bridge
services:
  pc2_experience_tracker:
    build:
      context: ../..
      dockerfile: docker/pc2_experience_tracker/Dockerfile
    command:
    - python
    - pc2_code/agents/experience_tracker.py
    container_name: pc2_experience_tracker
    depends_on:
    - redis
    - nats
    environment:
      HEALTH_PORT: '8160'
      LOG_LEVEL: INFO
      NATS_SERVERS: nats://nats_pc2_memory:4222
      PC2_ENVIRONMENT: 'true'
      PORT: '7160'
      PYTHONPATH: /app
      REDIS_HOST: redis_pc2_memory
      REDIS_PORT: '6379'
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8160/health
      timeout: 10s
    image: pc2_experience_tracker:latest
    networks:
    - pc2_experience_tracker_net
    ports:
    - 8260:7160
    - 8260:8160
    restart: unless-stopped
version: '3.8'
