services:
  # ---- Backend Services ----
  redis_reasoning:
    image: redis:7.2-alpine
    container_name: redis_reasoning
    ports:
      - "6389:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - reasoning_net

  nats_reasoning:
    image: nats:2.10-alpine
    container_name: nats_reasoning
    ports:
      - "4230:4222"
    volumes:
      - ./nats-server.conf:/config/nats-server.conf
    command: ["-c", "/config/nats-server.conf"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - reasoning_net

  # ---- Reasoning GPU Services ----
  chain_of_thought_agent:
    build:
      context: ../..
      dockerfile: docker/reasoning_gpu/Dockerfile
    image: reasoning_gpu:latest
    container_name: chain_of_thought_agent
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5612:5612"
      - "6612:6612"
    environment:
      - AGENT_NAME=ChainOfThoughtAgent
      - AGENT_PORT=5612
      - HEALTH_CHECK_PORT=6612
      - REDIS_URL=redis://redis_reasoning:6379
      - NATS_SERVERS=nats://nats_reasoning:4222
      - LOG_LEVEL=INFO
    depends_on:
      redis_reasoning:
        condition: service_healthy
      nats_reasoning:
        condition: service_started
    networks:
      - reasoning_net

  goto_agent:
    image: reasoning_gpu:latest
    container_name: goto_agent
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5646:5646"
      - "6646:6646"
    environment:
      - AGENT_NAME=GoTToTAgent
      - AGENT_PORT=5646
      - HEALTH_CHECK_PORT=6646
      - REDIS_URL=redis://redis_reasoning:6379
      - NATS_SERVERS=nats://nats_reasoning:4222
      - LOG_LEVEL=INFO
    depends_on:
      chain_of_thought_agent:
        condition: service_started
    networks:
      - reasoning_net

  cognitive_model_agent:
    image: reasoning_gpu:latest
    container_name: cognitive_model_agent
    command: ["python", "-m", "main_pc_code.agents.learning_manager"]
    ports:
      - "5641:5641"
      - "6641:6641"
    environment:
      - AGENT_NAME=CognitiveModelAgent
      - AGENT_PORT=5641
      - HEALTH_CHECK_PORT=6641
      - REDIS_URL=redis://redis_reasoning:6379
      - NATS_SERVERS=nats://nats_reasoning:4222
      - LOG_LEVEL=INFO
    depends_on:
      chain_of_thought_agent:
        condition: service_started
    networks:
      - reasoning_net

networks:
  reasoning_net:
    driver: bridge
