version: '3.8'
services:
  pc2_observability_hub:
    build:
      context: ../..
      dockerfile: docker/pc2_observability_hub/Dockerfile
    image: pc2_observability_hub:latest
    container_name: pc2_observability_hub
    command: ["python", "phase1_implementation/consolidated_agents/observability_hub/backup_observability_hub/observability_hub.py"]
    ports:
      - "9100:9100"  # Prometheus metrics port
      - "9110:9110"  # Health check port
    environment:
      LOG_LEVEL: INFO
      PYTHONPATH: /app
      REDIS_URL: redis://redis:6379/0
      NATS_SERVERS: nats://nats:4222
      PORT: "9100"
      HEALTH_PORT: "9110"
      PROMETHEUS_PORT: "9100"
      SCOPE: "pc2_agents"
      CROSS_MACHINE_SYNC: "true"
      MAINPC_OBS_HUB: "${MAINPC_OBS_HUB:-http://mainpc:9000}"
      PARALLEL_HEALTH_CHECKS: "true"
      PREDICTION_ENABLED: "true"
      PC2_ENVIRONMENT: 'true'
    depends_on:
      - redis
      - nats
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9110/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pc2_observability_hub_net

networks:
  pc2_observability_hub_net:
    driver: bridge