version: '3.8'

services:
  # ============================================================================
  # PC2 CONTAINER GROUP 1: MEMORY SERVICES (8 agents)
  # ============================================================================
  
  memory-services-group:
    build:
      context: ../../
      dockerfile: docker/pc2/Dockerfile.agent-group
    container_name: pc2-memory-services
    ports:
      - "7140:7140"  # MemoryOrchestratorService
      - "7102:7102"  # CacheManager
      - "7105:7105"  # UnifiedMemoryReasoningAgent
      - "7111:7111"  # ContextManager  
      - "7112:7112"  # ExperienceTracker
      - "8140:8140"  # Health checks
      - "8102:8102"
      - "8105:8105"
      - "8111:8111"
      - "8112:8112"
    volumes:
      - ../../logs:/app/logs
      - ../../data:/app/data
      - ../../cache:/app/cache
      - ../../config:/app/config
      - ../../pc2_code:/app/pc2_code
      - ../../common:/app/common
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONPATH=/app
      - GROUP_NAME=memory-services
      - AGENTS_LIST=MemoryOrchestratorService,CacheManager,UnifiedMemoryReasoningAgent,ContextManager,ExperienceTracker
    networks:
      - ai_system_network
    restart: unless-stopped

  # ============================================================================
  # PC2 CONTAINER GROUP 2: AI REASONING (5 agents)
  # ============================================================================
  
  ai-reasoning-group:
    build:
      context: ../../
      dockerfile: docker/pc2/Dockerfile.agent-group
    container_name: pc2-ai-reasoning
    ports:
      - "7104:7104"  # DreamWorldAgent
      - "7127:7127"  # DreamingModeAgent
      - "7108:7108"  # TutorAgent
      - "7131:7131"  # TutoringAgent
      - "7150:7150"  # VisionProcessingAgent
      - "8104:8104"  # Health checks
      - "8127:8127"
      - "8108:8108"
      - "8131:8131"
      - "8150:8150"
    volumes:
      - ../../logs:/app/logs
      - ../../data:/app/data
      - ../../cache:/app/cache
      - ../../config:/app/config
      - ../../pc2_code:/app/pc2_code
      - ../../common:/app/common
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONPATH=/app
      - GROUP_NAME=ai-reasoning
      - AGENTS_LIST=DreamWorldAgent,DreamingModeAgent,TutorAgent,TutoringAgent,VisionProcessingAgent
    networks:
      - ai_system_network
    restart: unless-stopped

  # ============================================================================
  # PC2 CONTAINER GROUP 3: WEB SERVICES (3 agents)
  # ============================================================================
  
  web-services-group:
    build:
      context: ../../
      dockerfile: docker/pc2/Dockerfile.agent-group
    container_name: pc2-web-services
    ports:
      - "7123:7123"  # FileSystemAssistantAgent
      - "7124:7124"  # RemoteConnectorAgent
      - "7126:7126"  # UnifiedWebAgent
      - "8123:8123"  # Health checks
      - "8124:8124"
      - "8126:8126"
    volumes:
      - ../../logs:/app/logs
      - ../../data:/app/data
      - ../../cache:/app/cache
      - ../../config:/app/config
      - ../../pc2_code:/app/pc2_code
      - ../../common:/app/common
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONPATH=/app
      - GROUP_NAME=web-services
      - AGENTS_LIST=FileSystemAssistantAgent,RemoteConnectorAgent,UnifiedWebAgent
    networks:
      - ai_system_network
    restart: unless-stopped

  # ============================================================================
  # PC2 CONTAINER GROUP 4: INFRASTRUCTURE (9 agents)
  # ============================================================================
  
  infrastructure-group:
    build:
      context: ../../
      dockerfile: docker/pc2/Dockerfile.agent-group
    container_name: pc2-infrastructure
    ports:
      - "7100:7100"  # TieredResponder
      - "7101:7101"  # AsyncProcessor  
      - "7113:7113"  # ResourceManager
      - "7115:7115"  # TaskScheduler
      - "7129:7129"  # AdvancedRouter
      - "7116:7116"  # AuthenticationAgent
      - "7118:7118"  # UnifiedUtilsAgent
      - "7119:7119"  # ProactiveContextMonitor
      - "7122:7122"  # AgentTrustScorer
      - "8100:8100"  # Health checks
      - "8101:8101"
      - "8113:8113"
      - "8115:8115"
      - "8129:8129"
      - "8116:8116"
      - "8118:8118"
      - "8119:8119"
      - "8122:8122"
    volumes:
      - ../../logs:/app/logs
      - ../../data:/app/data
      - ../../cache:/app/cache
      - ../../config:/app/config
      - ../../pc2_code:/app/pc2_code
      - ../../common:/app/common
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONPATH=/app
      - GROUP_NAME=infrastructure
      - AGENTS_LIST=TieredResponder,AsyncProcessor,ResourceManager,TaskScheduler,AdvancedRouter,AuthenticationAgent,UnifiedUtilsAgent,ProactiveContextMonitor,AgentTrustScorer
    networks:
      - ai_system_network
    restart: unless-stopped

  # ============================================================================
  # PC2 CONTAINER GROUP 5: OBSERVABILITY HUB FORWARDER (1 service)
  # ============================================================================
  
  observability-hub-forwarder:
    build:
      context: ../../
      dockerfile: docker/pc2/Dockerfile.agent-group
    container_name: pc2-observability-forwarder
    ports:
      - "9000:9000"     # API (PC2 ObservabilityHub)
      - "9100:9100"     # Health
    volumes:
      - ../../logs:/app/logs
      - ../../data:/app/data
      - ../../cache:/app/cache
      - ../../config:/app/config
      - ../../phase1_implementation:/app/phase1_implementation
      - ../../common:/app/common
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONPATH=/app
      - GROUP_NAME=observability-hub-forwarder
      - AGENTS_LIST=ObservabilityHub
      - PC2_MODE=true
      - MAINPC_HUB_ENDPOINT=http://mainpc-observability-hub:9000
    networks:
      - ai_system_network
    restart: unless-stopped

# ============================================================================
# NETWORKS & VOLUMES
# ============================================================================

networks:
  ai_system_network:
    external: true

volumes:
  pc2_data:
    driver: local
  pc2_cache:
    driver: local 