# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\"!\n\x0fScheduleRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"#\n\rScheduleReply\x12\x12\n\ntarget_gpu\x18\x01 \x01(\x05\x32M\n\x0cGPUScheduler\x12=\n\x05Query\x12\x1a.scheduler.ScheduleRequest\x1a\x18.scheduler.ScheduleReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULEREQUEST']._serialized_start=30
  _globals['_SCHEDULEREQUEST']._serialized_end=63
  _globals['_SCHEDULEREPLY']._serialized_start=65
  _globals['_SCHEDULEREPLY']._serialized_end=100
  _globals['_GPUSCHEDULER']._serialized_start=102
  _globals['_GPUSCHEDULER']._serialized_end=179
# @@protoc_insertion_point(module_scope)
