version: "3.9"

x-default-env: &default-env
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: DEBUG
  DEV_MODE: "true"

x-default-volumes: &default-volumes
  - ../:/workspace:rw            # mount full source tree
  - ~/.cache/pip:/home/app/.cache/pip

services:
  # ------------------------------------
  # MAINPC DEV CONTAINERS
  # ------------------------------------
  core_services:
    build: ../                    # project root Dockerfile
    command: >
      watchmedo auto-restart --patterns="*.py" --recursive -- \
      python -m main_pc_code.system_launcher --groups core_services
    environment:
      <<: *default-env
    volumes: *default-volumes
    networks: [backplane]

  gpu_intensive:
    build: ../
    command: >
      watchmedo auto-restart --patterns="*.py" --recursive -- \
      python -m main_pc_code.system_launcher --groups gpu_infrastructure,gpu_intensive
    environment:
      <<: *default-env
      NVIDIA_VISIBLE_DEVICES: "0"
    volumes: *default-volumes
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks: [backplane]

  # ------------------------------------
  # PC2 DEV CONTAINERS (runable on same host or remote)
  # ------------------------------------
  pc2_memory_processing:
    build: ../
    command: >
      watchmedo auto-restart --patterns="*.py" --recursive -- \
      python -m pc2_code.system_launcher --agent-names MemoryOrchestratorService,CacheManager,ContextManager,ExperienceTracker,UnifiedMemoryReasoningAgent
    environment:
      <<: *default-env
      REDIS_URL: redis://core_services:6379/0
    volumes: *default-volumes
    networks: [backplane]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    networks: [backplane]

networks:
  backplane:
    driver: bridge
