services:
  # ---- Backend Services ----
  redis_speech:
    image: redis:7.2-alpine
    container_name: redis_speech
    ports:
      - "6387:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - speech_net

  nats_speech:
    image: nats:2.10-alpine
    container_name: nats_speech
    ports:
      - "4229:4222"
    volumes:
      - ./nats-server.conf:/config/nats-server.conf
    command: ["-c", "/config/nats-server.conf"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - speech_net

  # ---- Speech GPU Services ----
  stt_service:
    build:
      context: ../..
      dockerfile: docker/speech_gpu/Dockerfile
    image: speech_gpu:latest
    container_name: stt_service
    command: ["python", "-m", "main_pc_code.agents.stt.dynamic_stt_manager"]
    ports:
      - "5551:5551"
      - "6551:6551"
    environment:
      - AGENT_NAME=STTService
      - AGENT_PORT=5551
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      redis_speech:
        condition: service_healthy
      nats_speech:
        condition: service_started
    networks:
      - speech_net

  tts_service:
    image: speech_gpu:latest
    container_name: tts_service
    command: ["python", "-m", "main_pc_code.agents.streaming_tts_agent"]
    ports:
      - "5552:5552"
      - "6552:6552"
    environment:
      - AGENT_NAME=TTSService
      - AGENT_PORT=5552
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  audio_capture:
    image: speech_gpu:latest
    container_name: audio_capture
    command: ["python", "-m", "main_pc_code.agents.streaming_audio_capture"]
    ports:
      - "5553:5553"
      - "6553:6553"
    environment:
      - AGENT_NAME=AudioCapture
      - AGENT_PORT=5553
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  fused_audio_preprocessor:
    image: speech_gpu:latest
    container_name: fused_audio_preprocessor
    command: ["python", "-m", "main_pc_code.agents.fused_audio_preprocessor"]
    ports:
      - "5554:5554"
      - "6554:6554"
    environment:
      - AGENT_NAME=FusedAudioPreprocessor
      - AGENT_PORT=5554
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  streaming_speech_recognition:
    image: speech_gpu:latest
    container_name: streaming_speech_recognition
    command: ["python", "-m", "main_pc_code.agents.streaming_speech_recognition"]
    ports:
      - "5555:5555"
      - "6555:6555"
    environment:
      - AGENT_NAME=StreamingSpeechRecognition
      - AGENT_PORT=5555
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  streaming_tts_agent:
    image: speech_gpu:latest
    container_name: streaming_tts_agent
    command: ["python", "-m", "main_pc_code.agents.streaming_tts_agent"]
    ports:
      - "5556:5556"
      - "6556:6556"
    environment:
      - AGENT_NAME=StreamingTTSAgent
      - AGENT_PORT=5556
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  wake_word_detector:
    image: speech_gpu:latest
    container_name: wake_word_detector
    command: ["python", "-m", "main_pc_code.agents.wake_word_detector"]
    ports:
      - "5557:5557"
      - "6557:6557"
    environment:
      - AGENT_NAME=WakeWordDetector
      - AGENT_PORT=5557
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
      - PORCUPINE_ACCESS_KEY=NUv4S1SW3VoT8vbF5XLn6nn2+czHtMsEX3U+YM42LwPTAtiNjSpkww==
      - WAKE_WORD_PATH=/app/main_pc_code/config/wake_words/High-minds_en_linux_v3_0_0.ppn
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  streaming_interrupt_handler:
    image: speech_gpu:latest
    container_name: streaming_interrupt_handler
    command: ["python", "-m", "main_pc_code.agents.streaming_interrupt_handler"]
    ports:
      - "5558:5558"
      - "6558:6558"
    environment:
      - AGENT_NAME=StreamingInterruptHandler
      - AGENT_PORT=5558
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

  streaming_language_analyzer:
    image: speech_gpu:latest
    container_name: streaming_language_analyzer
    command: ["python", "-m", "main_pc_code.agents.streaming_language_analyzer"]
    ports:
      - "5559:5559"
      - "6559:6559"
    environment:
      - AGENT_NAME=StreamingLanguageAnalyzer
      - AGENT_PORT=5559
      - REDIS_URL=redis://redis_speech:6379
      - NATS_SERVERS=nats://nats_speech:4222
      - LOG_LEVEL=INFO
    depends_on:
      stt_service:
        condition: service_started
    networks:
      - speech_net

networks:
  speech_net:
    driver: bridge
