# Memory System Environment Variables
# Standardized environment variables for memory-related components

# Memory Orchestrator Service (PC2)
MEMORY_ORCHESTRATOR_HOST: ${PC2_IP}
MEMORY_ORCHESTRATOR_PORT: 7140
MEMORY_ORCHESTRATOR_ADDR: tcp://${MEMORY_ORCHESTRATOR_HOST}:${MEMORY_ORCHESTRATOR_PORT}

# Memory Storage Configuration
MEMORY_SQLITE_PATH: data/unified_memory.db
MEMORY_REDIS_HOST: ${PC2_IP}
MEMORY_REDIS_PORT: 6379
MEMORY_REDIS_PASSWORD: ""
MEMORY_REDIS_DB: 0

# Memory Client Configuration
MEMORY_CLIENT_PORT: 5713
MEMORY_CLIENT_REQUEST_TIMEOUT: 5000  # milliseconds
MEMORY_CLIENT_CONNECTION_RETRY_INTERVAL: 10  # seconds
MEMORY_CLIENT_FAILURE_THRESHOLD: 3
MEMORY_CLIENT_RESET_TIMEOUT: 60  # seconds

# Context Manager Configuration
CONTEXT_MANAGER_PORT: 5716
CONTEXT_MANAGER_HEALTH_PORT: 6716
CONTEXT_MANAGER_MAX_CONTEXT_SIZE: 10000
CONTEXT_MANAGER_DEFAULT_TTL: 3600  # seconds

# Memory Lifecycle Management
MEMORY_LIFECYCLE_INTERVAL: 3600  # seconds
MEMORY_SHORT_TERM_TTL: 86400  # 24 hours
MEMORY_MEDIUM_TERM_TTL: 604800  # 7 days
MEMORY_CONSOLIDATION_THRESHOLD: 0.7
MEMORY_DECAY_RATE: 0.1 