# Network Configuration for AI System
# This file defines the network topology and connection parameters

# Environment-aware configuration
environment:
  # The environment will be loaded from ENV_TYPE
  development:
    use_local_mode: true
    mainpc_ip: '127.0.0.1'
    pc2_ip: '127.0.0.1'
    bind_address: '0.0.0.0'
    service_discovery_timeout: 5000
    secure_zmq: false
    metrics_enabled: false

  production:
    use_local_mode: false
    mainpc_ip: '${MAINPC_IP}'
    pc2_ip: '${PC2_IP}'
    bind_address: '0.0.0.0'
    service_discovery_timeout: 10000
    secure_zmq: true
    metrics_enabled: true

# Machine definitions
machines:
  mainpc:
    ip: '127.0.0.1'
    description: 'Main PC running core agents'
    hostname: 'mainpc'
    roles: ['coordinator', 'memory', 'models']

  pc2:
    ip: '127.0.0.1'
    description: 'Secondary PC running auxiliary agents'
    hostname: 'pc2'
    roles: ['vision', 'audio']

# Default values if environment variables are not set
defaults:
  mainpc_ip: '127.0.0.1'
  pc2_ip: '127.0.0.1'
  bind_address: '0.0.0.0'
  service_discovery_timeout: 5000
  service_discovery_retries: 3
  secure_zmq: false
  metrics_enabled: false

# Default binding settings
service_discovery_port: 5990 # Port for the service discovery mechanism

# Security settings
zmq_key_directory: 'certificates' # Directory containing ZMQ curve certificates

# Network architecture parameters
connection_timeout: 5000 # Default connection timeout in milliseconds
heartbeat_interval: 30 # Heartbeat interval in seconds
max_retries: 3 # Maximum connection retry attempts

# System-wide service ports
ports:
  system_digital_twin: 7120
  health_check: 8100
  unified_memory_reasoning: 7230 # Example port for UnifiedMemoryReasoningAgent

  # Core services
  coordinator: 26002
  task_router: 5571
  tts_connector: 5562
  health_monitor: 5584
  model_manager: 5570

  # Vision system
  vision_capture: 5587
  vision_processing: 5588

  # Translation services
  nllb_adapter: 5581
  phi_translation: 11434
  consolidated_translator: 5563

  # Memory system
  memory_orchestrator: 5575
  contextual_memory: 5576

  # Web/external interfaces
  remote_connector: 5557
  web_assistant: 5589

  # PC2 services
  pc2_agent: 5560
  unified_web_agent: 7550

  # New ports for the new system
  chain_of_thought: 5612
  got_tot: 7000
  self_training_orchestrator: 5644
  emotion_engine: 5590
  audio_capture: 6575
