# Central Port Registry
# Single source of truth for all port assignments across MainPC and PC2
# Format: port, purpose, owner (machine/service)

# MainPC Core Services (5000-5999 range)
- port: 5000
  purpose: Model Manager Suite / Local Fine Tuner
  owner: MainPC

- port: 5001
  purpose: Model Manager Suite Health Check
  owner: MainPC

- port: 5557
  purpose: Remote Connector Agent (connects to PC2)
  owner: PC2

- port: 5560
  purpose: Face Recognition Agent
  owner: MainPC

- port: 5562
  purpose: XTTS Agent / Streaming TTS
  owner: MainPC

- port: 5563
  purpose: Consolidated Translator / PC2 Translator
  owner: PC2

- port: 5570
  purpose: Streaming Audio Capture / Model Manager
  owner: MainPC

- port: 5571
  purpose: Task Router / Streaming Speech Recognition
  owner: MainPC

- port: 5572
  purpose: Streaming Language Analyzer
  owner: MainPC

- port: 5573
  purpose: Fixed Streaming Translation
  owner: MainPC

- port: 5574
  purpose: Streaming Text Processor / Streaming TTS
  owner: MainPC

- port: 5575
  purpose: Memory Orchestrator / Streaming Interrupt Handler
  owner: MainPC

- port: 5576
  purpose: Memory Client / Streaming Interrupt Handler Output
  owner: MainPC

- port: 5577
  purpose: Memory Client
  owner: MainPC

- port: 5578
  purpose: Knowledge Base
  owner: MainPC

- port: 5579
  purpose: Learning Manager / Streaming Language Analyzer
  owner: MainPC

- port: 5580
  purpose: Mood Tracker Agent
  owner: MainPC

- port: 5581
  purpose: NLLB Translation Adapter
  owner: PC2

- port: 5584
  purpose: Fixed Streaming Translation / Health Monitor
  owner: MainPC

- port: 5587
  purpose: Vision Capture
  owner: MainPC

- port: 5588
  purpose: Learning Manager / Vision Processing
  owner: MainPC

- port: 5589
  purpose: Web Assistant
  owner: MainPC

- port: 5590
  purpose: Emotion Engine / Memory Agent Base
  owner: MainPC

- port: 5592
  purpose: Vision Capture Agent
  owner: MainPC

- port: 5595
  purpose: Translation Service / Context Bridge
  owner: MainPC

- port: 5596
  purpose: Contextual Memory Agent
  owner: PC2

- port: 5597
  purpose: Digital Twin Agent / Episodic Memory
  owner: PC2

- port: 5598
  purpose: Enhanced Model Router / Jarvis Memory
  owner: MainPC

- port: 5599
  purpose: Dream World Agent / Learning Mode
  owner: PC2

- port: 5600
  purpose: Voice Profiling Agent / ZMQ Bridge / Cognitive Model
  owner: MainPC

- port: 5605
  purpose: Tutor Agent / Auto Fixer
  owner: PC2

- port: 5606
  purpose: Filesystem Assistant / Executor
  owner: MainPC

- port: 5610
  purpose: Context Summarizer / Face Recognition
  owner: MainPC

- port: 5611
  purpose: Error Pattern Memory / Health Check
  owner: PC2

- port: 5612
  purpose: Chain of Thought Agent
  owner: MainPC

- port: 5613
  purpose: Predictive Health Monitor / Test Generator
  owner: MainPC

- port: 5615
  purpose: TinyLlama Service Enhanced
  owner: PC2

- port: 5620
  purpose: Self Training Orchestrator / Autonomous Web Assistant
  owner: PC2

- port: 5624
  purpose: Proactive Agent
  owner: MainPC

- port: 5625
  purpose: Tone Detector
  owner: MainPC

- port: 5626
  purpose: Agent Trust Scorer
  owner: PC2

- port: 5628
  purpose: TTS Cache
  owner: MainPC

- port: 5630
  purpose: Meta Cognition Agent / Predictive Health Monitor
  owner: MainPC

- port: 5634
  purpose: Unified Planning Agent
  owner: MainPC

- port: 5636
  purpose: Feedback Handler
  owner: MainPC

- port: 5637
  purpose: Responder
  owner: MainPC

- port: 5638
  purpose: Active Learning Monitor
  owner: MainPC

- port: 5639
  purpose: Multi Agent Swarm Manager
  owner: MainPC

- port: 5640
  purpose: Unified System Agent
  owner: MainPC

- port: 5641
  purpose: Cognitive Model Agent
  owner: MainPC

- port: 5642
  purpose: Human Awareness Agent / Local Fine Tuner
  owner: MainPC

- port: 5643
  purpose: Emotion Synthesis Agent / Learning Adjuster
  owner: MainPC

- port: 5644
  purpose: Self Training Orchestrator
  owner: MainPC

- port: 5645
  purpose: Local Fine Tuner Agent
  owner: MainPC

- port: 5646
  purpose: GOT TOT Agent
  owner: MainPC

- port: 5650
  purpose: Code Generator / Tutoring Agent
  owner: PC2

- port: 5660
  purpose: TinyLlama Service Enhanced
  owner: MainPC

- port: 5701
  purpose: Intention Validator Agent
  owner: MainPC

- port: 5703
  purpose: Empathy Agent
  owner: MainPC

- port: 5704
  purpose: Mood Tracker Agent
  owner: MainPC

- port: 5705
  purpose: Human Awareness Agent
  owner: MainPC

- port: 5706
  purpose: Emotion Synthesis Agent
  owner: MainPC

- port: 5708
  purpose: Voice Profiling Agent
  owner: MainPC

- port: 5709
  purpose: NLU Agent
  owner: MainPC

- port: 5710
  purpose: Advanced Command Handler
  owner: MainPC

- port: 5711
  purpose: Chitchat Agent
  owner: MainPC

- port: 5713
  purpose: Memory Client
  owner: MainPC

- port: 6000
  purpose: Code Generator
  owner: MainPC

- port: 6001
  purpose: Executor
  owner: MainPC

- port: 6002
  purpose: Progressive Generator
  owner: MainPC

- port: 6003
  purpose: Auto-Fixer
  owner: MainPC

- port: 6004
  purpose: Test Generator
  owner: MainPC

- port: 6071
  purpose: Media Pose Detector
  owner: MainPC

- port: 6550
  purpose: Audio Capture
  owner: MainPC

- port: 6551
  purpose: Fused Audio Preprocessor
  owner: MainPC

- port: 6552
  purpose: Wake Word Detector
  owner: MainPC

- port: 6553
  purpose: Streaming Speech Recognition
  owner: MainPC

- port: 6575
  purpose: Audio Capture
  owner: MainPC

- port: 6577
  purpose: Wake Word Detector
  owner: MainPC

- port: 6580
  purpose: Streaming Speech Recognition
  owner: MainPC

- port: 6581
  purpose: Language and Translation Coordinator
  owner: MainPC

# PC2 Services (7000-7999 range)
- port: 7000
  purpose: GOT TOT Agent
  owner: PC2

- port: 7100
  purpose: Tiered Responder / Service Registry
  owner: PC2

- port: 7101
  purpose: Async Processor
  owner: PC2

- port: 7102
  purpose: Cache Manager
  owner: PC2

- port: 7103
  purpose: Performance Monitor
  owner: PC2

- port: 7104
  purpose: Dream World Agent
  owner: PC2

- port: 7105
  purpose: Unified Memory Reasoning Agent
  owner: PC2

- port: 7106
  purpose: Episodic Memory Agent
  owner: PC2

- port: 7107
  purpose: Learning Agent
  owner: PC2

- port: 7108
  purpose: Tutoring Agent
  owner: PC2

- port: 7109
  purpose: Knowledge Base Agent
  owner: PC2

- port: 7110
  purpose: Memory Manager
  owner: PC2

- port: 7111
  purpose: Context Manager
  owner: PC2

- port: 7112
  purpose: Experience Tracker
  owner: PC2

- port: 7113
  purpose: Resource Manager
  owner: PC2

- port: 7115
  purpose: Task Scheduler Agent
  owner: PC2

- port: 7116
  purpose: Authentication Agent
  owner: PC2

- port: 7118
  purpose: Unified Utils Agent
  owner: PC2

- port: 7119
  purpose: Proactive Context Monitor
  owner: PC2

- port: 7120
  purpose: System Digital Twin
  owner: PC2

- port: 7124
  purpose: Remote Connector Agent
  owner: PC2

- port: 7126
  purpose: Unified Web Agent
  owner: PC2

- port: 7127
  purpose: Dreaming Mode Agent
  owner: PC2

- port: 7128
  purpose: Performance Logger Agent
  owner: PC2

- port: 7129
  purpose: Advanced Router
  owner: PC2

- port: 7131
  purpose: Tutoring Agent
  owner: PC2

- port: 7140
  purpose: Memory Orchestrator Service
  owner: PC2

- port: 7150
  purpose: Vision Processing Agent / Error Bus
  owner: PC2

- port: 7200
  purpose: Learning Opportunity Detector / Observability Hub
  owner: PC2

- port: 7210
  purpose: Learning Orchestration Service / Model Orchestrator
  owner: MainPC

- port: 7220
  purpose: System Digital Twin / Model Evaluation Framework
  owner: MainPC

# Health Check Ports (8000-8999 range)
- port: 8010
  purpose: Model Orchestrator Health Check
  owner: MainPC

- port: 8100
  purpose: Service Registry Health / Tiered Responder Health
  owner: PC2

- port: 8101
  purpose: Async Processor Health
  owner: PC2

- port: 8102
  purpose: Cache Manager Health
  owner: PC2

- port: 8103
  purpose: Performance Monitor Health
  owner: PC2

- port: 8104
  purpose: Dream World Agent Health
  owner: PC2

- port: 8105
  purpose: Unified Memory Reasoning Health
  owner: PC2

- port: 8106
  purpose: Episodic Memory Agent Health
  owner: PC2

- port: 8107
  purpose: Learning Agent Health
  owner: PC2

- port: 8108
  purpose: Tutoring Agent Health
  owner: PC2

- port: 8109
  purpose: Knowledge Base Agent Health
  owner: PC2

- port: 8110
  purpose: Memory Manager Health
  owner: PC2

- port: 8111
  purpose: Context Manager Health
  owner: PC2

- port: 8112
  purpose: Experience Tracker Health
  owner: PC2

- port: 8113
  purpose: Resource Manager Health
  owner: PC2

- port: 8115
  purpose: Task Scheduler Health
  owner: PC2

- port: 8116
  purpose: Authentication Agent Health
  owner: PC2

- port: 8118
  purpose: Unified Utils Agent Health
  owner: PC2

- port: 8119
  purpose: Proactive Context Monitor Health
  owner: PC2

- port: 8120
  purpose: System Digital Twin Health
  owner: PC2

- port: 8124
  purpose: Remote Connector Health
  owner: PC2

- port: 8126
  purpose: Unified Web Agent Health
  owner: PC2

- port: 8127
  purpose: Dreaming Mode Agent Health
  owner: PC2

- port: 8128
  purpose: Performance Logger Health
  owner: PC2

- port: 8129
  purpose: Advanced Router Health
  owner: PC2

- port: 8131
  purpose: Tutoring Agent Health
  owner: PC2

- port: 8200
  purpose: Observability Hub Health
  owner: MainPC

- port: 8212
  purpose: Learning Orchestration Health
  owner: MainPC

- port: 8220
  purpose: System Digital Twin Health
  owner: MainPC

# Special Ports
- port: 9000
  purpose: Observability Hub (Backup)
  owner: PC2

- port: 26002
  purpose: Request Coordinator
  owner: MainPC 