networks:
  chain_of_thought_agent_net:
    driver: bridge
services:
  chain_of_thought_agent:
    build:
      context: ../..
      dockerfile: docker/chain_of_thought_agent/Dockerfile
    command:
    - python
    - -m
    - main_pc_code.agents.learning_manager
    container_name: chain_of_thought_agent
    depends_on:
    - redis_reasoning
    - nats_reasoning
    environment:
      AGENT_NAME: ChainOfThoughtAgent
      AGENT_PORT: '5612'
      HEALTH_CHECK_PORT: '6612'
      LOG_LEVEL: INFO
      NATS_SERVERS: nats://nats_reasoning:4222
      REDIS_URL: redis://redis_reasoning:6379
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6612/health
      timeout: 10s
    image: chain_of_thought_agent:latest
    networks:
    - chain_of_thought_agent_net
    ports:
    - 5612:5612
    - 6612:6612
    restart: unless-stopped
version: '3.8'
