services:
  # Backend services (shared with coordination)  
  redis:
    image: redis:7.2-alpine
    container_name: redis_observability
    ports:
      - "6380:6379"  # Different port to avoid conflict
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Observability Hub (metrics, monitoring, health)
  observability_hub:
    build:
      context: ../..
      dockerfile: docker/observability/Dockerfile
    image: observability:latest
    container_name: observability_hub
    command: ["python", "-m", "phase1_implementation.consolidated_agents.observability_hub.backup_observability_hub.observability_hub"]
    environment:
      LOG_LEVEL: "INFO"
      REDIS_HOST: "redis_observability"
      REDIS_PORT: "6379"
    ports:
      - "9000:9000"  # Main observability port
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
