#!/bin/bash
# PC2 Shared Base Image Build Script
# Auto-generated by PC2 dependency clustering
# Implements 70-80% build time reduction strategy

set -euo pipefail

REGISTRY="ghcr.io/haymayndzultra"
TAG_PREFIX="pc2-base"
AGENT_TAG="pc2-latest"

echo "🚀 Building PC2 shared base images..."

# Build base images

echo "📦 Building utility base image..."
docker buildx build     -f docker/base/pc2_base_utility.Dockerfile     -t ${REGISTRY}/utility:${TAG_PREFIX}-latest     --build-arg BUILDKIT_INLINE_CACHE=1     --cache-from ${REGISTRY}/utility:${TAG_PREFIX}-latest     --push     .

echo "📦 Building deep_learning base image..."
docker buildx build     -f docker/base/pc2_base_deep_learning.Dockerfile     -t ${REGISTRY}/deep_learning:${TAG_PREFIX}-latest     --build-arg BUILDKIT_INLINE_CACHE=1     --cache-from ${REGISTRY}/deep_learning:${TAG_PREFIX}-latest     --push     .

echo "🎯 Building individual PC2 agents..."

# Agent builds (will use cached base layers)

echo "Building TaskScheduler..."
docker buildx build     -f docker/pc2_taskscheduler/Dockerfile     -t ${REGISTRY}/taskscheduler:${AGENT_TAG}     --build-arg BASE_CLUSTER=utility     --build-arg BUILDKIT_INLINE_CACHE=1     --cache-from ${REGISTRY}/taskscheduler:${AGENT_TAG}     --push     .

echo "Building ResourceManager..."
docker buildx build     -f docker/pc2_resourcemanager/Dockerfile     -t ${REGISTRY}/resourcemanager:${AGENT_TAG}     --build-arg BASE_CLUSTER=utility     --build-arg BUILDKIT_INLINE_CACHE=1     --cache-from ${REGISTRY}/resourcemanager:${AGENT_TAG}     --push     .

echo "Building TieredResponder..."
docker buildx build     -f docker/pc2_tieredresponder/Dockerfile     -t ${REGISTRY}/tieredresponder:${AGENT_TAG}     --build-arg BASE_CLUSTER=deep_learning     --build-arg BUILDKIT_INLINE_CACHE=1     --cache-from ${REGISTRY}/tieredresponder:${AGENT_TAG}     --push     .

echo "✅ All PC2 builds complete!"
echo "⏱️  Expected time reduction: 70-80% vs individual builds"
