# AI System Startup Configuration
# Defines the startup sequence and dependencies for all agents

# Global settings
settings:
  default_startup_timeout: 30  # seconds
  health_check_interval: 15    # seconds
  max_restart_attempts: 3
  error_bus_port: 7150
  error_bus_host: ${PC2_IP}

# Core infrastructure agents (must start first)
core_agents:
  - name: ErrorBus
    script: src/core/error_bus.py
    port: 7150
    dependencies: []
    critical: true
    
  - name: ServiceRegistry
    script: src/core/service_registry.py
    port: 7151
    dependencies: [ErrorBus]
    critical: true
    
  - name: HealthMonitor
    script: src/core/health_monitor.py
    port: 7152
    health_port: 7153
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true
    
  - name: MemoryClient
    script: agents/memory_client.py
    port: 5713
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true

# Memory system agents
memory_agents:
  - name: SessionMemoryAgent
    script: agents/session_memory_agent.py
    port: 5574
    health_port: 6583
    dependencies: [MemoryClient, ErrorBus]
    critical: true
    
  - name: KnowledgeBase
    script: agents/knowledge_base.py
    port: 5715
    health_port: 6715
    dependencies: [MemoryClient, ErrorBus]
    critical: true
    
  - name: ContextManager
    script: agents/context_manager.py
    port: 5716
    health_port: 6716
    dependencies: [MemoryClient, ErrorBus, SessionMemoryAgent]
    critical: true

# Input processing agents
input_agents:
  - name: SpeechToText
    script: agents/stt/dynamic_stt_manager.py
    port: 5560
    health_port: 6560
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true
    
  - name: IntentRecognizer
    script: agents/intent_recognizer.py
    port: 5561
    health_port: 6561
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient]
    critical: true
    
  - name: InputProcessor
    script: agents/input_processor.py
    port: 5562
    health_port: 6562
    dependencies: [SpeechToText, IntentRecognizer, SessionMemoryAgent]
    critical: true

# Core processing agents
processing_agents:
  - name: RequestCoordinator
    script: agents/request_coordinator.py
    port: 5570
    health_port: 6570
    dependencies: [ErrorBus, ServiceRegistry, SessionMemoryAgent, ContextManager]
    critical: true
    
  - name: ModelOrchestrator
    script: agents/model_orchestrator.py
    port: 5571
    health_port: 6571
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient, ContextManager]
    critical: true
    
  - name: GoalManager
    script: agents/goal_manager.py
    port: 5572
    health_port: 6572
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient]
    critical: true

# Output processing agents
output_agents:
  - name: ResponseGenerator
    script: agents/response_generator.py
    port: 5580
    health_port: 6580
    dependencies: [ModelOrchestrator, MemoryClient]
    critical: true
    
  - name: TranslationService
    script: agents/translation_service.py
    port: 5581
    health_port: 6581
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient]
    critical: false
    
  - name: StreamingTTS
    script: agents/core_speech_output/streaming_tts_agent.py
    port: 5582
    health_port: 6582
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true

# Utility agents
utility_agents:
  - name: SystemDigitalTwin
    script: agents/system_digital_twin.py
    port: 5590
    health_port: 6590
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient]
    critical: false
    
  - name: ActiveLearningMonitor
    script: agents/active_learning_monitor.py
    port: 5591
    health_port: 6591
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient]
    critical: false
    
  - name: ContextSummarizer
    script: agents/core_memory/context_summarizer_agent.py
    port: 5592
    health_port: 6592
    dependencies: [ErrorBus, ServiceRegistry, MemoryClient, ContextManager]
    critical: false