# UNIFIED-SYSTEM PROFILE: CORE
# Minimal essential agents for basic conversational functionality
# Total agents: 16 (essential only, no optional)

profile:
  name: core
  description: "Minimal core system - basic conversational AI"
  
# Agent selection rules
agent_selection:
  # Include all infrastructure and coordination agents
  include_groups:
    - infrastructure_registry
    - coordination_resource
    - memory_foundation
    
  # Include minimal speech I/O
  include_agents:
    - AudioCapture
    - STTService
    - TTSService
    - StreamingTTSAgent
    
  # Exclude PC2 agents for minimal profile
  exclude_groups:
    - pc2_core
    
  # No optional agents in core profile
  optional_agents: false
  
# Resource limits for core profile
resource_overrides:
  global_settings:
    resource_limits:
      cpu_percent: 50
      memory_mb: 2048
      max_threads: 4
      
# Startup parameters
startup:
  timeout_seconds: 60
  health_check_retries: 5
  parallel_starts: 3