# UNIFIED-SYSTEM PROFILE: VISION
# Core system + vision processing capabilities
# Total agents: ~20 (essential + vision optional)

profile:
  name: vision
  description: "Core system with vision processing capabilities"
  
# Agent selection rules
agent_selection:
  # Include all core essential agents
  include_groups:
    - infrastructure_registry
    - coordination_resource
    - memory_foundation
    - speech_io
    
  # Enable vision optional agents
  optional_agents:
    include:
      - FaceRecognitionAgent
      - VisionProcessingAgent
      
  # Auto-load vision agents on startup
  autoload_on_startup:
    - FaceRecognitionAgent
    - VisionProcessingAgent
    
# Resource limits for vision profile
resource_overrides:
  global_settings:
    resource_limits:
      cpu_percent: 70
      memory_mb: 4096
      max_threads: 6
      
  # Vision agents need more VRAM
  agent_overrides:
    FaceRecognitionAgent:
      vram_mb: 1024
    VisionProcessingAgent:
      vram_mb: 1024
      
# Startup parameters
startup:
  timeout_seconds: 90
  health_check_retries: 10
  parallel_starts: 4