version: '3.8'

services:
  model_manager_suite_test:
    image: language_stack:latest
    container_name: model_manager_suite_test
    command: ["python", "-m", "main_pc_code.model_manager_suite", "--port", "7721", "--health-port", "8721"]
    environment:
      - AGENT_NAME=ModelManagerSuite
      - AGENT_PORT=7721
      - HEALTH_PORT=8721
    ports:
      - "7721:7721"
      - "8721:8721"
    networks:
      - language_net

  # Phase 4.2: MMA service removed - replaced by model_manager_suite in main compose
  
  # Phase 4.2: Legacy test service removed - MMS now in main compose
