# PC2 Startup Configuration
# Defines the startup sequence and dependencies for all PC2 agents

# Global settings
settings:
  default_startup_timeout: 30  # seconds
  health_check_interval: 15    # seconds
  max_restart_attempts: 3
  error_bus_port: 7150

# Core infrastructure agents (must start first)
core_agents:
  - name: ErrorBus
    script: src/core/error_bus.py
    port: 7150
    dependencies: []
    critical: true
    
  - name: ServiceRegistry
    script: src/core/service_registry.py
    port: 7151
    dependencies: [ErrorBus]
    critical: true
    
  - name: HealthMonitor
    script: src/core/health_monitor.py
    port: 7152
    health_port: 7153
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true

# Memory system agents
memory_agents:
  - name: MemoryOrchestratorService
    script: agents/memory_orchestrator_service.py
    port: 7140
    health_port: 7141
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true
    
  - name: MemoryScheduler
    script: agents/memory_scheduler.py
    port: 7142
    health_port: 7143
    dependencies: [ErrorBus, ServiceRegistry, MemoryOrchestratorService]
    critical: true
    
  - name: SystemHealthManager
    script: agents/ForPC2/system_health_manager.py
    port: 7144
    health_port: 7145
    dependencies: [ErrorBus, ServiceRegistry, MemoryOrchestratorService, MemoryScheduler]
    critical: true

# Input processing agents
input_agents:
  - name: AudioPreprocessor
    script: agents/audio_preprocessor.py
    port: 6560
    health_port: 6561
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true
    
  - name: VoiceActivityDetector
    script: agents/voice_activity_detector.py
    port: 6562
    health_port: 6563
    dependencies: [ErrorBus, ServiceRegistry, AudioPreprocessor]
    critical: true

# Model serving agents
model_agents:
  - name: ModelServer
    script: agents/model_server.py
    port: 6570
    health_port: 6571
    dependencies: [ErrorBus, ServiceRegistry]
    critical: true
    
  - name: EmbeddingService
    script: agents/embedding_service.py
    port: 6572
    health_port: 6573
    dependencies: [ErrorBus, ServiceRegistry, ModelServer]
    critical: true
    
  - name: TranslationModelService
    script: agents/translation_model_service.py
    port: 6574
    health_port: 6575
    dependencies: [ErrorBus, ServiceRegistry, ModelServer]
    critical: false

# Utility agents
utility_agents:
  - name: LogAggregator
    script: agents/log_aggregator.py
    port: 6580
    health_port: 6581
    dependencies: [ErrorBus, ServiceRegistry]
    critical: false
    
  - name: MetricsCollector
    script: agents/metrics_collector.py
    port: 6582
    health_port: 6583
    dependencies: [ErrorBus, ServiceRegistry]
    critical: false
    
  - name: BackupManager
    script: agents/backup_manager.py
    port: 6584
    health_port: 6585
    dependencies: [ErrorBus, ServiceRegistry, MemoryOrchestratorService]
    critical: false
