# Canonical Startup Configuration for PC2 Sub-System
# Forged by CASCADE - Single Source of Truth

# PC2 Services (Agents)
pc2_services:
  # Phase 1 - Integration Layer Agents
  - { name: TieredResponder, script_path: agents/tiered_responder.py, host: localhost, port: 7100, required: true, dependencies: [] }
  - { name: AsyncProcessor, script_path: agents/async_processor.py, host: localhost, port: 7101, required: true, dependencies: [] }
  - { name: CacheManager, script_path: agents/cache_manager.py, host: localhost, port: 7102, required: true, dependencies: [] }
  - { name: PerformanceMonitor, script_path: agents/performance_monitor.py, host: localhost, port: 7103, required: true, dependencies: [] }

  # Phase 2 - PC2-Specific Core Agents
  - { name: DreamWorldAgent, script_path: agents/DreamWorldAgent.py, host: localhost, port: 7104, dependencies: [UnifiedMemoryReasoningAgent], required: true }
  - { name: UnifiedMemoryReasoningAgent, script_path: agents/UnifiedMemoryReasoningAgent.py, host: localhost, port: 7105, dependencies: [CacheManager], required: true }
  - { name: EpisodicMemoryAgent, script_path: agents/EpisodicMemoryAgent.py, host: localhost, port: 7106, dependencies: [UnifiedMemoryReasoningAgent], required: true }
  - { name: LearningAgent, script_path: agents/LearningAdjusterAgent.py, host: localhost, port: 7107, dependencies: [EpisodicMemoryAgent], required: true }
  - { name: TutoringAgent, script_path: agents/tutoring_agent.py, host: localhost, port: 7108, required: true, dependencies: [] }
  - { name: KnowledgeBaseAgent, script_path: agents/knowledge_base_agent.py, host: localhost, port: 7109, dependencies: [CacheManager], required: true }
  - { name: MemoryManager, script_path: agents/memory_manager.py, host: localhost, port: 7110, dependencies: [UnifiedMemoryReasoningAgent], required: true }
  - { name: ContextManager, script_path: agents/context_manager.py, host: localhost, port: 7111, dependencies: [MemoryManager], required: true }
  - { name: ExperienceTracker, script_path: agents/experience_tracker.py, host: localhost, port: 7112, dependencies: [EpisodicMemoryAgent], required: true }
  - { name: ResourceManager, script_path: agents/resource_manager.py, host: localhost, port: 7113, required: true, dependencies: [] }
  - { name: HealthMonitor, script_path: agents/health_monitor.py, host: localhost, port: 7114, required: true, dependencies: [] }
  - { name: TaskScheduler, script_path: agents/task_scheduler.py, host: localhost, port: 7115, dependencies: [AsyncProcessor], required: true }

  # ForPC2 Agents (PC2-Specific Services)
  - { name: AuthenticationAgent, script_path: agents/ForPC2/AuthenticationAgent.py, host: localhost, port: 7116, required: true, dependencies: [] }
  - { name: UnifiedErrorAgent, script_path: agents/ForPC2/unified_error_agent.py, host: localhost, port: 7117, required: true, dependencies: [] }
  - { name: UnifiedUtilsAgent, script_path: agents/ForPC2/unified_utils_agent.py, host: localhost, port: 7118, required: true, dependencies: [] }
  - { name: ProactiveContextMonitor, script_path: agents/ForPC2/proactive_context_monitor.py, host: localhost, port: 7119, dependencies: [ContextManager], required: true }
  - { name: SystemDigitalTwin, script_path: agents/ForPC2/system_digital_twin.py, host: localhost, port: 7120, required: true, dependencies: [] }
  - { name: RCAAgent, script_path: agents/ForPC2/rca_agent.py, host: localhost, port: 7121, dependencies: [HealthMonitor], required: true }

  # Additional PC2 Core Agents
  - { name: AgentTrustScorer, script_path: agents/AgentTrustScorer.py, host: localhost, port: 7122, required: true, dependencies: [] }
  - { name: FileSystemAssistantAgent, script_path: agents/filesystem_assistant_agent.py, host: localhost, port: 7123, required: true, dependencies: [] }
  - { name: RemoteConnectorAgent, script_path: agents/remote_connector_agent.py, host: localhost, port: 7124, required: true, dependencies: [] }
  - { name: SelfHealingAgent, script_path: agents/self_healing_agent.py, host: localhost, port: 7125, required: true, dependencies: [] }
  - { name: UnifiedWebAgent, script_path: agents/unified_web_agent.py, host: localhost, port: 7126, required: true, dependencies: [] }
  - { name: DreamingModeAgent, script_path: agents/DreamingModeAgent.py, host: localhost, port: 7127, dependencies: [DreamWorldAgent], required: true }
  - { name: PerformanceLoggerAgent, script_path: agents/PerformanceLoggerAgent.py, host: localhost, port: 7128, required: true, dependencies: [] }
  - { name: AdvancedRouter, script_path: agents/advanced_router.py, host: localhost, port: 7129, required: true, dependencies: [] }

# Environment variables for all agents
environment:
  PYTHONPATH: "${PYTHONPATH}:${PWD}/.."
  LOG_LEVEL: "INFO"
  DEBUG_MODE: "false"

# Resource limits for all agents
resource_limits:
  cpu_percent: 80
  memory_mb: 4096
  max_threads: 8

# Health check configuration
health_checks:
  interval_seconds: 30
  timeout_seconds: 10
  retries: 3
  start_period_seconds: 300

# PC2 Network Configuration
pc2_network:
  host: "127.0.0.1"
  agent_ports:
    start: 7100
    end: 7199
