version: '3.8'
services:
  pc2_agent_trust_scorer:
    build:
      context: ../..
      dockerfile: docker/pc2_agent_trust_scorer/Dockerfile
    image: pc2_agent_trust_scorer:latest
    container_name: pc2_agent_trust_scorer
    command: ["python", "-m", "pc2_code.agents.AgentTrustScorer"]
    ports:
      - "8122:7122"  # Service port mapped to PC-2 range
      - "8122:8122"  # Health check port
    environment:
      LOG_LEVEL: INFO
      PYTHONPATH: /app
      REDIS_URL: redis://redis:6379/0
      NATS_SERVERS: nats://nats:4222
      PORT: "7122"
      HEALTH_PORT: "8122"
      PC2_ENVIRONMENT: 'true'
    depends_on:
      - redis
      - nats
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8122/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pc2_agent_trust_scorer_net

networks:
  pc2_agent_trust_scorer_net:
    driver: bridge