version: '3.8'
services:
  pc2_proactive_context_monitor:
    build:
      context: ../..
      dockerfile: docker/pc2_proactive_context_monitor/Dockerfile
    image: pc2_proactive_context_monitor:latest
    container_name: pc2_proactive_context_monitor
    command: ["python", "-m", "pc2_code.agents.ForPC2.proactive_context_monitor"]
    ports:
      - "8119:7119"  # Service port mapped to PC-2 range
      - "8119:8119"  # Health check port
    environment:
      LOG_LEVEL: INFO
      PYTHONPATH: /app
      REDIS_URL: redis://redis:6379/0
      NATS_SERVERS: nats://nats:4222
      PORT: "7119"
      HEALTH_PORT: "8119"
      PC2_ENVIRONMENT: 'true'
    depends_on:
      - redis
      - nats
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8119/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pc2_proactive_context_monitor_net

networks:
  pc2_proactive_context_monitor_net:
    driver: bridge