networks:
  pc2_vision_processing_agent_net:
    driver: bridge
services:
  pc2_vision_processing_agent:
    build:
      context: ../..
      dockerfile: docker/pc2_vision_processing_agent/Dockerfile
    command:
    - python
    - pc2_code/agents/VisionProcessingAgent.py
    container_name: pc2_vision_processing_agent
    depends_on:
    - redis
    - nats
    environment:
      HEALTH_PORT: '8150'
      LOG_LEVEL: INFO
      NATS_SERVERS: nats://nats_pc2_vision:4222
      PC2_ENVIRONMENT: 'true'
      PORT: '7150'
      PYTHONPATH: /app
      REDIS_URL: redis://redis_pc2_vision:6379/0
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8150/health
      timeout: 10s
    image: pc2_vision_processing_agent:latest
    networks:
    - pc2_vision_processing_agent_net
    ports:
    - 8450:7150
    - 8450:8150
    restart: unless-stopped
version: '3.8'
