networks:
  pc2_filesystem_assistant_agent_net:
    driver: bridge
services:
  pc2_filesystem_assistant_agent:
    build:
      context: ../..
      dockerfile: docker/pc2_filesystem_assistant_agent/Dockerfile
    command:
    - python
    - pc2_code/agents/filesystem_assistant_agent.py
    container_name: pc2_filesystem_assistant_agent
    depends_on:
    - redis
    - nats
    environment:
      HEALTH_PORT: '8123'
      LOG_LEVEL: INFO
      NATS_SERVERS: nats://nats_pc2_utility:4222
      PC2_ENVIRONMENT: 'true'
      PORT: '7123'
      PYTHONPATH: /app
      REDIS_URL: redis://redis_pc2_utility:6379/1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8123/health
      timeout: 10s
    image: pc2_filesystem_assistant_agent:latest
    networks:
    - pc2_filesystem_assistant_agent_net
    ports:
    - 8423:7123
    - 8423:8123
    restart: unless-stopped
version: '3.8'
