networks:
  pc2_advanced_router_net:
    driver: bridge
services:
  pc2_advanced_router:
    build:
      context: ../..
      dockerfile: docker/pc2_advanced_router/Dockerfile
    command:
    - python
    - pc2_code/agents/advanced_router.py
    container_name: pc2_advanced_router
    depends_on:
    - redis
    - nats
    environment:
      HEALTH_PORT: '8120'
      LOG_LEVEL: INFO
      NATS_SERVERS: nats://nats_pc2_async:4222
      PC2_ENVIRONMENT: 'true'
      PORT: '7120'
      PYTHONPATH: /app
      REDIS_URL: redis://redis_pc2_async:6379/3
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8120/health
      timeout: 10s
    image: pc2_advanced_router:latest
    networks:
    - pc2_advanced_router_net
    ports:
    - 8320:7120
    - 8320:8120
    restart: unless-stopped
version: '3.8'
