version: '3.8'
services:
  pc2_authentication_agent:
    build:
      context: ../..
      dockerfile: docker/pc2_authentication_agent/Dockerfile
    image: pc2_authentication_agent:latest
    container_name: pc2_authentication_agent
    command: ["python", "-m", "pc2_code.agents.ForPC2.AuthenticationAgent"]
    ports:
      - "8116:7116"  # Service port mapped to PC-2 range
      - "8116:8116"  # Health check port
    environment:
      LOG_LEVEL: INFO
      PYTHONPATH: /app
      REDIS_URL: redis://redis:6379/0
      NATS_SERVERS: nats://nats:4222
      PORT: "7116"
      HEALTH_PORT: "8116"
      PC2_ENVIRONMENT: 'true'
    depends_on:
      - redis
      - nats
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8116/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pc2_authentication_agent_net

networks:
  pc2_authentication_agent_net:
    driver: bridge