name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images (dev)
        run: |
          docker compose -f docker/docker-compose.dev.yml build
      - name: Run unit tests
        run: |
          pip install -r test-requirements.txt
          pytest -q
      - name: Push images on main
        if: github.ref == 'refs/heads/main'
        run: |
          docker compose -f docker/docker-compose.dev.yml push