name: AI-System CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.base.txt
      - name: Static port duplicate check & dry-run
        run: |
          python main_pc_code/system_launcher.py --dry-run --config main_pc_code/config/startup_config.yaml