name: Configuration Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*config*.yaml'
      - '**/*config*.yml'
      - 'common/validation/**'
      - 'scripts/validate_config.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*config*.yaml'
      - '**/*config*.yml'
      - 'common/validation/**'
      - 'scripts/validate_config.py'

jobs:
  validate-configs:
    runs-on: ubuntu-latest
    name: Validate Agent Configurations
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema
          
      - name: Validate MainPC Configuration
        run: |
          echo "🔍 Validating MainPC configuration..."
          python scripts/validate_config.py main_pc_code/config/startup_config.yaml --warn --verbose
        continue-on-error: true
        
      - name: Validate PC2 Configuration
        run: |
          echo "🔍 Validating PC2 configuration..."
          python scripts/validate_config.py pc2_code/config/startup_config.yaml --warn --verbose
        continue-on-error: true
        
      - name: Validate All Configurations (Summary)
        run: |
          echo "🔍 Running comprehensive validation..."
          python scripts/validate_config.py --all --warn --verbose
          
      - name: Test Schema Loading
        run: |
          echo "🧪 Testing schema loading..."
          python -c "
          from common.validation.config_validator import ConfigValidator
          validator = ConfigValidator()
          print('✅ Schema loaded successfully')
          print(f'Schema title: {validator.schema.get(\"title\", \"Unknown\")}')
          "
          
      - name: Configuration Report
        if: always()
        run: |
          echo "📊 Configuration Validation Summary"
          echo "=================================="
          echo "✅ JSON Schema validation framework active"
          echo "✅ CI pipeline validates on config changes"
          echo "⚠️  Currently in WARN mode (non-blocking)"
          echo ""
          echo "Next Phase 0 tasks:"
          echo "- Day 2: Script path resolution fixes"
          echo "- Day 3: Port audit and conflict resolution"
          echo "- Day 4: Logging infrastructure upgrade" 