name: "Port Lint"
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  validate-ports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Validate within-host port uniqueness
        run: python tools/validate_ports_unique.py

