name: Quarterly Re-Audit

on:
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch:

jobs:
  re-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.base.txt
      - name: Run hub audit
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python hub_membership_audit.py --repo . \
            --yaml main_pc_code/config/startup_config.yaml pc2_code/config/startup_config.yaml \
            --hubs AffectiveProcessingCenter RealTimeAudioPipeline ModelOpsCoordinator UnifiedObservabilityCenter MemoryFusionHub \
            --outdir audits/
          python verify_hub_inclusion.py
      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audits-quarterly
          path: audits/*.csv
          retention-days: 30