name: UOC CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r unified_observability_center/requirements.txt
          python -m pip install -r unified_observability_center/requirements-dev.txt
      - name: Run focused tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q unified_observability_center/tests