version: '3.8'
services:
  pc2_unified_utils_agent:
    build:
      context: ../..
      dockerfile: docker/pc2_unified_utils_agent/Dockerfile
    image: pc2_unified_utils_agent:latest
    container_name: pc2_unified_utils_agent
    command: ["python", "-m", "pc2_code.agents.ForPC2.unified_utils_agent"]
    ports:
      - "8118:7118"  # Service port mapped to PC-2 range
      - "8118:8118"  # Health check port
    environment:
      LOG_LEVEL: INFO
      PYTHONPATH: /app
      REDIS_URL: redis://redis:6379/0
      NATS_SERVERS: nats://nats:4222
      PORT: "7118"
      HEALTH_PORT: "8118"
      PC2_ENVIRONMENT: 'true'
      UTILS_MODE: "comprehensive"
      MAX_CONCURRENT_TASKS: "10"
      TIMEOUT_SECONDS: "300"
    depends_on:
      - redis
      - nats
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8118/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pc2_unified_utils_agent_net

networks:
  pc2_unified_utils_agent_net:
    driver: bridge