version: '3.9'

# This file defines the shared networks for the AI system
# It should be included in all docker-compose setups

networks:
  ai_system_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

  # Separate network for more sensitive services
  ai_internal_network:
    driver: bridge
    internal: true  # This network has no external connectivity
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

  # External-facing network for web services
  ai_external_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1 