version: '3.8'

# Shared Network Configuration for MainPC and PC2 Communication

networks:
  ai-shared-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1 