version: '3.8'

x-gpu: &with-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  # Example override; extend any service by adding this file to docker compose -f stack
  modelmanager-suite:
    <<: *with-gpu
  vrm-optimizer:
    <<: *with-gpu