# Shared Network Configuration for MainPC-PC2 Docker Communication
version: '3.8'

# External network for cross-machine communication
networks:
  ai_system_cross_machine:
    driver: bridge
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

# Host network mapping for development
# Use host networking mode for cross-machine communication
# MainPC: 192.168.100.16
# PC2: 192.168.100.17 